# Generated by Django 5.1.5 on 2025-01-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='items/images'),
        ),
    ]
